### ISSUE TITLE
How can I change the road network parameters?

### ISSUE THREAD

**Issue by kosmylo** [StanfordASL/AMoD-toolkit#14]
It is not clear to me from where I can change the parameters of the road network, for example how many nodes exist and how many chargers. I can notice that these parameters exist inside the `EAMoDspecDemo.mat`, and there exists a function called `LoadScenario`. Are these two related? I cannot understand where the variable `scenario` comes from. Could anyone help me understand this part and how can we go from the parameters to the actual graph of the road network?

**Comment by estandiaa** [comment]
1. The code to create `EAMoDspecDemo.mat` is not public. You'll have to write your own code to create the variables that are in that file. 

2. `LoadScenario`  is not related to  `EAMoDspecDemo.mat`. scenario comes from a legacy data format that we were using in the past. See https://github.com/StanfordASL/AMoD-toolkit/blob/8635d3e299cca7826cf3d4539e092274d8187679/Test/HelperFunctions/LoadScenario.m

**Comment by kosmylo** [comment]
Thank you for your answer. Is there anywhere in the code a part that creates the road network or everything related to it is just imported?

**Comment by estandiaa** [comment]
It is just imported. You can create it using something like this: https://osmnx.readthedocs.io/en/stable/
